# Generated by Django 4.0.5 on 2022-07-02 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20220702_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='images',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 19, 42, 21, 250348)),
        ),
    ]
