# Generated by Django 3.2.13 on 2022-07-04 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_imagemodel_image_imagemodel_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 12, 33, 5, 388104)),
        ),
    ]
